---
AWSTemplateFormatVersion: "2010-09-09"
Description: Frontdesk Web Application

Parameters:
  KeyName:
    Description: SSH Public Key
    Type: AWS::SSM::Parameter::Value<AWS::EC2::KeyPair::KeyName>
    Default: /Frontdesk/KeyName

  VpcId:
    Description: VPC ID
    Type: AWS::SSM::Parameter::Value<AWS::EC2::VPC::Id>
    Default: /Frontdesk/VpcId

  PrimarySubnetId:
    Description: Primary Subnet ID
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Subnet::Id>
    Default: /Frontdesk/PrimarySubnetId

  SecondarySubnetId:
    Description: Secondary Subnet ID
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Subnet::Id>
    Default: /Frontdesk/SecondarySubnetId

  WebImageId:
    Description: Web Instance Image ID
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /Frontdesk/WebImageId

  HostedZoneId:
    Description: Hosted Zone ID
    Type: AWS::SSM::Parameter::Value<AWS::Route53::HostedZone::Id>
    Default: /Frontdesk/HostedZoneId

  DomainName:
    Description: Public Second-Level Domain Name
    Type: AWS::SSM::Parameter::Value<String>
    Default: /Frontdesk/DomainName

  CertificateArn:
    Description: Public Domain SSL Certificate
    Type: AWS::SSM::Parameter::Value<String>
    Default: /Frontdesk/CertificateArn

Resources:
  # Deployment
  DeploymentBucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Project
          Value: Frontdesk

  # Common Resources
  ManagementSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH from anywhere
      VpcId:
        Ref: VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: Management
        - Key: Project
          Value: Frontdesk

  # Web Stack
  WebInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: Text2PrintWebInstance
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: AllowReadSecrets
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - ssm:GetParameters
                Resource:
                  Fn::Sub:
                    - "arn:aws:ssm:${Region}:${Account}:parameter/Frontdesk/*"
                    - Region: !Ref "AWS::Region"
                      Account: !Ref "AWS::AccountId"
        - PolicyName: AllowGetDeployments
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - s3:ListBucket
                  - s3:GetBucketLocation
                Resource:
                  Fn::Sub: "${DeploymentBucket.Arn}"
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource:
                  Fn::Sub: "${DeploymentBucket.Arn}/*"

  WebInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: Text2PrintWebInstance
      Roles:
        - Ref: WebInstanceRole

  WebSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    DependsOn: LoadBalancerSecurityGroup
    Properties:
      GroupDescription: Allow HTTP from load balancer
      VpcId:
        Ref: VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          SourceSecurityGroupId:
            Ref: LoadBalancerSecurityGroup
      Tags:
        - Key: Name
          Value: Frontdesk Web Instance
        - Key: Project
          Value: Frontdesk

  WebLaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      LaunchConfigurationName: Frontdesk Web Instance
      InstanceType: t3.micro
      KeyName:
        Ref: KeyName
      IamInstanceProfile:
        Ref: WebInstanceProfile
      ImageId:
        Ref: WebImageId
      InstanceMonitoring: false
      AssociatePublicIpAddress: true
      SecurityGroups:
        - Ref: ManagementSecurityGroup
        - Ref: WebSecurityGroup

  WebAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    DependsOn: WebTargetGroup
    Properties:
      LaunchConfigurationName:
        Ref: WebLaunchConfiguration
      MinSize: 1
      MaxSize: 3
      DesiredCapacity: 2
      VPCZoneIdentifier:
        - Ref: PrimarySubnetId
        - Ref: SecondarySubnetId
      TargetGroupARNs:
        - Ref: WebTargetGroup
      Tags:
        - Key: Project
          Value: Frontdesk
    UpdatePolicy:
      AutoScalingRollingUpdate:
        MaxBatchSize: 1
        MinInstancesInService: 2
        PauseTime: PT5M

  # Load Balancer
  LoadBalancerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId:
        Ref: VpcId
      GroupDescription: Allow HTTPS from anywhere
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: Frontdesk Load Balancer
        - Key: Project
          Value: Frontdesk

  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Type: application
      Scheme: internet-facing
      SecurityGroups:
        - Ref: LoadBalancerSecurityGroup
      Subnets:
        - Ref: PrimarySubnetId
        - Ref: SecondarySubnetId
      Tags:
        - Key: Name
          Value: Frontdesk Load Balancer
        - Key: Project
          Value: Frontdesk

  WebTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId:
        Ref: VpcId
      HealthCheckPath: /
      HealthCheckProtocol: HTTP
      HealthCheckIntervalSeconds: 30
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 2
      Port: 80
      Protocol: HTTP
      TargetType: instance
      Tags:
        - Key: Name
          Value: Frontdesk Web Instance
        - Key: Project
          Value: Frontdesk

  LoadBalancerListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn:
        Ref: LoadBalancer
      Port: 443
      Protocol: HTTPS
      Certificates:
        - CertificateArn:
            Ref: CertificateArn
      DefaultActions:
        - Type: forward
          TargetGroupArn:
            Ref: WebTargetGroup

  # Domains
  ApplicationDomain:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId:
        Ref: HostedZoneId
      Name:
        Ref: DomainName
      Type: A
      AliasTarget:
        DNSName:
          Fn::GetAtt: ["LoadBalancer", "DNSName"]
        EvaluateTargetHealth: false
        HostedZoneId:
          Fn::GetAtt: ["LoadBalancer", "CanonicalHostedZoneID"]

Outputs:
  ApplicationUrl:
    Description: Web Application Url
    Value:
      Fn::Sub: "https://${DomainName}/"
