---
- name: install utilities
  apt:
    state: present
    name:
      - htop

- name: configure motd
  template:
    src: etc/motd
    dest: /etc/motd
    owner: root
    group: root
    mode: 0644
