---
- name: install python
  apt:
    state: present
    name:
      - python3
      - python3-requests  # used by deployment scripts
      - python3-boto3     # used by deployment scripts
      - python3-distutils # used by Twitter PEX to unpack itself
